#!/bin/bash
###############################
# Resource Manager Directives #
###############################

### Run using command -v tissue=tissue_name, chrom=chromosome_number, alpha=alpha, window=window

### Select the shell you would like to script to execute within.
#PBS -S /bin/bash
### Inform the scheduler of the expected runtime, where
### walltime=HH:MM:SS.
#PBS -l walltime=16:00:00
### Inform the scheduler of the number of CPU cores for your job.
#PBS -l nodes=1:ppn=1
### Inform the scheduler of the amount of memory you expect
### to use. Use units of ‘b’, ‘kb’, ‘mb’, or ‘gb’.
#PBS -l mem=8gb
### Set the destination for your program’s output: stdout and stderr.
#PBS -e ./${PBS_JOBNAME}.e${PBS_JOBID}
#PBS -o ./${PBS_JOBNAME}.o${PBS_JOBID}
 
#################
# Job Execution #
#################

module load R/3.1.0
Rscript ./create_model.R $study $expr_RDS $geno $gene_annot $snp_annot \
    $n_k_folds $alpha $out_dir $chrom $snpset $window
